### ISSUE TITLE
I Can't get my docker compose working.

### ISSUE THREAD

**Issue by Nostradamus1973** [habitual69/thetvappstream#5]
Good afternoon,

I created a Docker Compose and can't seem to get it working, I keep getting a deployment error.
This is what I have so far:

```
version: "3.1"
services:
  thetvappstream:
    container_name: thetvappstream
    environment:
      - TZ=America/New_York
    image: habitual69/thetvappstream:latest
    ports:
      - 7705:5000     # Web Interface Port
    volumes:
      - /home/nostradamus/dockers/thetvappstream:/app/data/
    restart: unless-stopped

```
This docker compose file will run on 7705(change it to whatever you'd like), I have it set to run in "dockers" in my Home folder.
When I go to http://localhost:7705/channels.m3u I get nothing, looks like the m3u is blank.
I'm not sure if I'm doing something wrong, or, if the there's something else going on.

Thank you and have a nice day.
